install: 
	pip install -r requirements.txt
	
# issue with sklearn: https://stackoverflow.com/questions/46113732/modulenotfounderror-no-module-named-sklearn
sklearn:
	pip3 install -U scikit-learn scipy matplotlib